# Production-specific Bun configuration
[install]
exact = false
production = false
optional = true
prefer = "online"

[build]
outdir = "./dist"
target = "bun"
minify = true
sourcemap = "external"
splitting = false
treeshake = false
optimize = "size"
compress = false
format = "esm"

[run]
hot = false
watch = false

[test]
timeout = 10000
